apiVersion: cache.rawdatalabs.cloud/v1alpha1
kind: KafkaMigration
metadata:
  name: kafka-mirror-maker
spec:
  # version: 2.3.0
  # replicas: 1
  consumer:
    # zookeeperConnect: 127.0.0.1:2181
    bootstrapServers: 'my-source-cluster-kafka-bootstrap:9092'
    groupId: my-source-group-id
  producer:
    bootstrapServers: 'my-target-cluster-kafka-bootstrap:9092'
  whitelist: .*
