apiVersion: cache.rawdatalabs.cloud/v1alpha1
kind: Migration
metadata:
  name: example-postgresql-migration
spec:
  # Add fields here
  backupFilePath: /tmp/backup.tar
  backupFormat: tar
  databaseDriver: postgresql
  dump: 
    hostname: postgresql-persistent.development.svc
    port: "5432"
    database: inventory
    username: postgres
    password: postgres
  restore: 
    hostname: postgresql.devtest.svc
    port: "5432"
    database: inventory
    username: postgres
    password: postgres
    # @optional  - not used yet



