apiVersion: cache.rawdatalabs.cloud/v1alpha1
kind: PostgresqlMigration
metadata:
  name: example-postgresql-migration
  namespace: tutorial
spec:
  backupFilePath: /tmp/backup.tar
  backupFormat: tar
  databaseDriver: postgresql
  dump: 
    hostname: postgresql.development.svc
    port: "5432"
    database: inventory
    username: postgres
    password: postgres
  restore: 
    hostname: postgresql.staging.svc
    port: "5432"
    database: inventory
    username: postgres
    password: postgres



