kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jigger-operator
subjects:
- kind: ServiceAccount
  name: jigger-operator
  namespace: "*"
roleRef:
  kind: ClusterRole
  name: jigger-operator
  apiGroup: rbac.authorization.k8s.io