---
# image: quay.io/rawdatalabs/alpine-kubectl
# tasks file for rawdata.pvc_migration_role
- name: start PVC Migration Job
  k8s:
   state: present
   definition: "{{ lookup('template', 'new-job.yml.j2') }}"
   namespace: "{{ meta.namespace }}"

