---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: cache.rawdatalabs.cloud/jigger-operator:testing
  tasks:
  - name: Create the cache.rawdatalabs.cloud/v1alpha1.Migration
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/cache_v1alpha1_migration_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='cache.rawdatalabs.cloud', api_version='v1alpha1', kind='Migration', namespace=namespace, resource_name=cr.metadata.name) }}"
    vars:
      cr: "{{ lookup('file', '/'.join([deploy_dir, 'crds/cache_v1alpha1_migration_cr.yaml'])) | from_yaml }}"

- import_playbook: "{{ playbook_dir }}/../default/asserts.yml"
