---
# tasks file for rawdata.kafka_mirrormaker_role
# @TODO

- name: start kafka migration job
  k8s:
   state: present
   definition: "{{ lookup('template', 'mirrormaker-job-bundle.yml.j2') }}"
   namespace: "{{ meta.namespace }}"
