---
# tasks file for postgresql
- name: start postgresql migration job
  k8s:
    definition:
      kind: Job
      metadata:
        name: metadata
      spec:
        template:
          spec:
            volumes:
            - name: tmp
              emptyDir: {}
            containers:
            - name: export-pod
              image: ''
              volumeMounts:
              - name: tmp
                mountPath: "/tmp"
              command:
              - bash
              - "-c"
              - pg_dump --dbname=postgresql://{{dump.username}}:{{dump.password}}@{{dump.hostname}}:{{dump.port}}/{{dump.database}} -v -h {{dump.hostname}} -p {{dump.port}} --format={{dump.backupFormat}} -f {{dump.backupFilePath}}
              - &&
              - pg_restore --dbname=postgresql://{{restore.username}}:{{restore.password}}@{{restore.service}}:{{restore.port}}/{{restore.database}} -v -C -h {{restore.service}} -p {{restore.port}} --format={{restore.backupFormat}}  {{restore.backupFilePath}}
            restartPolicy: OnFailure
        backoffLimit: '4'



