---
# tasks file for postgresql
- name: start postgresql migration job
  k8s:
    definition:
      kind: Job
      metadata:
        name: "{{ meta.name }}"
        namespace: "{{ meta.namespace }}"
      spec:
        template:
          spec:
            volumes:
            - name: tmp
              emptyDir: {}
            containers:
            - name: export-pod
              image: 'quay.io/rawdatalabs/postgresql-96-rhel7:latest'
              volumeMounts:
              - name: tmp
                mountPath: "/tmp"
              command:
              - bash
              - "-c"
              - "pg_dump --dbname=postgresql://{{ dump.username }}:{{ dump.password }}@{{ dump.hostname }}:{{ dump.port }}/{{ dump.database }} -v -h {{ dump.hostname }} -p {{ dump.port }} --format={{ dump.backup_format }} -f {{ dump.backup_file_path }}  && pg_restore --dbname=postgresql://{{ restore.username }}:{{ restore.password }}@{{ restore.service }}:{{ restore.port }}/{{ restore.database }} -v -C -h {{ restore.service }} -p {{ restore.port }} --format={{ restore.backup_format }}  {{ restore.backup_file_path }}"
            restartPolicy: OnFailure
        backoffLimit: '4'



